[program:linda-seeds-api_laravel-queue-listeners]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --max-jobs=50
directory=/usr/src/app
autostart=true
autorestart=true
numprocs=4
startretries=3
user=www-data
exitcodes=0,1
stopsignal=TERM
logfile_maxbytes=20MB
logfile_backups=30
stderr_logfile=/usr/src/app/storage/logs/queue/error.log
stdout_logfile=/usr/src/app/storage/logs/queue/output.log


[program:linda-seeds-api_laravel-order-payment-log-queue-listeners]
process_name=%(process_num)02d
command=php artisan queue:work --queue=order_payment_log --max-jobs=1000
directory=/usr/src/app
autostart=true
autorestart=true
numprocs=4
startretries=3
user=www-data
exitcodes=0,1
stopsignal=TERM
logfile_maxbytes=20MB
logfile_backups=30
stderr_logfile=/usr/src/app/storage/logs/queue/order_payment_log_error.log
stdout_logfile=/usr/src/app/storage/logs/queue/order_payment_log_output.log
