server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;
    server_name localhost;

    access_log access.log main;
    error_log  error.log;

    root /usr/src/app/public;
    index index.php;

    client_max_body_size 2048m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
        add_header  Host              $http_host;   # required for docker client's sake
        add_header  X-Real-IP         $remote_addr; # pass on real client's IP
    }

    location ~ \.php$ {
        proxy_read_timeout 300;
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # deny access to dot files, but not .well-known
    # deny or return 404
    location ~ /\.(?!well-known).* {
    	   return 404;
    	   # deny all;
    }
}
