; opcache
opcache.memory_consumption=256
;opcache.validate_timestamps=0
;
; uncomment for configure preload
;
;opcache.preload=/usr/src/app/config/preload.php
;opcache.preload_user=www-data
opcache.max_accelerated_files=10000
